const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const code=fs.readFileSync(require('node:path').join(__dirname,'../../app/static/instagram-connect.js'),'utf8');
function element(){return {children:[],listeners:{},disabled:false,checked:false,textContent:'',classList:{toggle(){}},append(...n){this.children.push(...n)},appendChild(n){this.children.push(n)},replaceChildren(){this.children=[]},addEventListener(n,fn){this.listeners[n]=fn}}}
function setup(fetch){const nodes=Object.fromEntries(['account-grid','status','continue-btn'].map(id=>[id,element()]));const navigated=[];const context={document:{getElementById:id=>nodes[id],createElement:element},fetch,AbortController,setTimeout,clearTimeout,window:{location:{assign:u=>navigated.push(u)}}};vm.runInNewContext(code,context);return {nodes,navigated}}
const settle=()=>new Promise(r=>setImmediate(r));const account={ig_user_id:'11',fb_page_id:'22',username:'<fixture>',name:'Fixture'};
test('one account requires an explicit choice and names stay text',async()=>{const calls=[];const {nodes}=setup(async url=>{calls.push(url);return {ok:true,json:async()=>url.endsWith('available')?[account]:[]}});await settle();assert.equal(calls.length,2);assert.equal(nodes['continue-btn'].disabled,true);const label=nodes['account-grid'].children[0];assert.equal(label.children[1].textContent,'@<fixture>');assert.equal('innerHTML' in label,false);label.children[0].checked=true;label.children[0].listeners.change();assert.equal(nodes['continue-btn'].disabled,false)});
test('existing account can refresh; double submit is suppressed and failure is recoverable',async()=>{let finish,posts=0;const {nodes,navigated}=setup(async url=>{if(url.endsWith('select')){posts++;return await new Promise(r=>finish=r)}return {ok:true,json:async()=>url.endsWith('available')?[account]:['11']}});await settle();const input=nodes['account-grid'].children[0].children[0];input.checked=true;input.listeners.change();const first=nodes['continue-btn'].listeners.click();await nodes['continue-btn'].listeners.click();assert.equal(posts,1);assert.equal(nodes['continue-btn'].disabled,true);assert.equal(input.disabled,true);finish({ok:false,json:async()=>({detail:'Connection expired. Please start again.'})});await first;assert.equal(nodes['continue-btn'].disabled,false);assert.equal(navigated.length,0);assert.equal(input.disabled,false);assert.match(nodes.status.textContent,/expired/)});
test('expired discovery is visible and cannot submit',async()=>{const {nodes}=setup(async()=>({ok:false,json:async()=>({detail:'Connection expired. Please start again.'})}));await settle();assert.match(nodes.status.textContent,/expired/);assert.equal(nodes['continue-btn'].disabled,true)});
test('successful choice submits returned page identity once and opens workspace',async()=>{let saved;const {nodes,navigated}=setup(async(url,options)=>{if(url.endsWith('select')){saved=JSON.parse(options.body);return {ok:true,json:async()=>({ok:true})}}return {ok:true,json:async()=>url.endsWith('available')?[account]:[]}});await settle();const input=nodes['account-grid'].children[0].children[0];input.checked=true;input.listeners.change();await nodes['continue-btn'].listeners.click();assert.deepEqual(saved,[{ig_user_id:'11',page_id:'22'}]);assert.deepEqual(navigated,['/app'])});
