"""Build an offline phone-size review for the bounded Vision family experiment."""
import argparse
from collections import Counter
import json
from pathlib import Path

HTML = '''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Sabeel Vision · Family evidence</title><style>
*{box-sizing:border-box}body{margin:0;background:#eeeae1;color:#23352c;font:16px/1.6 system-ui,sans-serif}main{max-width:1180px;margin:auto;padding:32px 20px}h1{font-size:clamp(30px,5vw,54px);line-height:1.12;max-width:800px}h2{font-size:23px}p{max-width:850px}.eyebrow{font-size:12px;text-transform:uppercase;letter-spacing:.15em}.notice{background:#fff8e8;border-left:4px solid #a66335;padding:16px}.stats{display:flex;gap:24px;flex-wrap:wrap;font-weight:650}select,button{font:inherit;min-height:44px;padding:8px;border:1px solid #a8b1a5;border-radius:8px;background:#fff;color:inherit}label{display:flex;flex-direction:column;font-size:13px;gap:4px}.controls{display:flex;flex-wrap:wrap;gap:12px;margin:20px 0}.pair{display:flex;gap:28px;align-items:start;flex-wrap:wrap}.phone{width:var(--phone,320px);flex:none}.phone img{display:block;width:100%;box-shadow:0 12px 35px #24382e20}.phone h3{font-size:15px}.detail{flex:1;min-width:220px;max-width:620px}button:disabled{opacity:.4}.nav{display:flex;align-items:center;gap:12px;margin:16px 0}details{background:#fff9;border:1px solid #d1d2c8;padding:14px;border-radius:10px;margin:14px 0}summary{cursor:pointer;min-height:36px}pre{white-space:pre-wrap;overflow-wrap:anywhere;font-size:12px}.gallery{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:16px}.gallery img{width:100%}.gallery figure{margin:0}.gallery figcaption{font-size:12px}.badge{font-size:12px;padding:5px 9px;background:#dce6db;border-radius:5px}a{color:#286744}table{border-collapse:collapse;width:100%;font-size:14px}td,th{padding:12px;text-align:left;border-bottom:1px solid #c7cabb;vertical-align:top}.scroll{overflow:auto}.sheet{display:flex;gap:18px;align-items:start}.sheet figure{width:320px;margin:0;flex:none}.sheet img{width:320px;display:block}.sheet figcaption{font-size:11px;min-height:50px}.small{font-size:13px;color:#526154}@media(max-width:500px){main{padding:24px 14px}.phone{max-width:100%}}
</style><main id="main"><div class="eyebrow">Sabeel Studio · 8 October 2026 · Actual API outputs</div><h1>Fresh scenes.<br>The words still come first.</h1>
<p>A controlled test of three AI background families and both feed and Story formats; variation counts are shown in this batch. Exact verified sources, the same olive brand, and no optional reflection. These are synthetic illustrative scenes, not photographs of real sacred locations.</p>
<p class="notice"><strong>Experimental evaluation — not a creator-validated release.</strong> Automated contrast and source checks, Codex visual judgment, and external creator/source review are distinct. Human reviews have not occurred. Rejected compositions must not be published. No publishing or production data changes were performed by this experiment.</p>
<div class="stats" id="stats"></div>
<section id="assessment"></section>
<h2>Inspect the finished card</h2><p class="small">The photograph was composed for Qur’an 2:153, then reused with five other exact source records to expose density and reuse failures. That stress test does not measure new per-source generation success.</p>
<div class="controls"><label>Family<select id="family"></select></label><label>Variation<select id="variant"><option value="1">1</option><option value="2">2</option></select></label><label>Format<select id="format"><option value="feed_4_5">Feed · 4:5</option><option value="story_9_16">Story · 9:16</option></select></label><label>Source<select id="source"></select></label><label>Phone width<select id="width"><option>320</option><option>390</option></select></label></div>
<div class="pair"><div class="phone"><h3 id="label"></h3><img id="card" alt="Actual composed source card"><div class="nav"><button id="prev">Previous</button><span id="page"></span><button id="next">Next</button></div></div><div class="detail"><p id="status"></p><p id="notes"></p><details><summary>Raw generated background</summary><img id="raw" style="width:100%" alt="Background before source typography"></details><details><summary>Exact source and returned metadata</summary><pre id="record"></pre></details><details><summary>Automated evidence and errors</summary><pre id="audit"></pre></details></div></div>
<h2>All generated backgrounds</h2><p>These are the actual outputs. No image was replaced to improve the reported success rate.</p><div id="gallery" class="gallery"></div>
<h2>Current trends and the competitive bar</h2><p>These are platform trend signals and documented product features, not a ranking of Muslim creators’ preferences or an independent competitor performance test.</p><ul>
<li><a href="https://www.canva.com/design-trends/">Canva’s 2026 design trends</a> emphasize tactile surfaces, human expression and structured simplicity alongside more experimental directions. For Sabeel, the restrained and tactile directions are the useful ones.</li>
<li><a href="https://business.adobe.com/blog/connectioneering-creative-trend-human-connection-ai-era">Adobe’s September 2026 analysis</a> emphasizes relatable, emotionally meaningful imagery. It supports natural materials and ordinary settings; it does not prove that our specific families improve engagement.</li>
<li><a href="https://www.canva.com/help/create-onbrand-images-with-ai/">Canva</a> documents brand-photo-guided generation, aspect-ratio selection, saved assets and further editing. Generation plus creative control is already a competitive expectation.</li>
<li><a href="https://helpx.adobe.com/ca/firefly/web/work-with-images/generate-images/reference-images-for-styling.html">Adobe Firefly</a> documents reusable style references; <a href="https://developer.adobe.com/firefly-services/docs/firefly-api/guides/concepts/structure-image-reference/">its composition references</a> provide a separate control over spatial structure. Sabeel should distinguish identity from composition.</li>
<li><a href="https://akhirahprojects.com/akhirah-designer/">Akhirah Designer</a> documents source insertion, mobile editing, layers, typography controls and export. Sabeel’s proposed advantage is less preparation work from verified source to reviewed, scheduled post, while preserving editing freedom. That advantage still needs creator testing.</li></ul>
<h2>What to reuse and what to rework</h2><div class="scroll"><table><tr><th>Keep and extend</th><th>Replace or substantially revise</th></tr><tr><td>Canonical source/card separation; RAQM typography; exact source slices; brand kit; saved media manifests; Cloudinary ownership receipts; draft recovery; publishing validation and idempotency.</td><td>Square-centered family prompts; overlapping legacy catalogs; generic prompt-hash variation; heavy contrast washes; photo-strip-only composition; family-specific background reuse; preview/automation routing drift.</td></tr></table></div>
<p>The full scene pipeline must plan text before generation, validate the decoded export, reject unsuitable images without erasing them, preserve approved backgrounds across layout changes, and use the same services in Studio and automations. Historical saved drafts must remain compatible.</p>
<details><summary>Experiment boundaries</summary><p>OpenAI-only, current configured model and medium quality. Bounded generation attempts recorded before each request; no automatic retry after an uncertain request. The prototype uses the canonical source builder, sequence planner and typography painter, with full-background placement and a maximum 20% light wash. The compact batch groups attribution beneath the source; balanced/refined batches also use the established continuation reading scale for medium sources and stronger fallback ink. Existing production defaults are unchanged by this experiment. More than ten pages remains blocked. Phone-width previews are not physical-device or human-creator validation.</p></details>
</main><script>
const rows=__ROWS__, generations=__GENERATIONS__, sources=__SOURCES__, assessment=__ASSESSMENT__;
const $=id=>document.getElementById(id),families={luxury_editorial:'Material Editorial',desert_glow:'Desert Light',midnight_oasis:'Quiet Night',emerald_forest:'Quiet Nature'};let page=0;
Object.entries(families).filter(([v])=>rows.some(r=>r.family===v)).forEach(([v,t])=>$('family').add(new Option(t,v)));sources.forEach(s=>$('source').add(new Option(s.record.reference+' · '+s.key,s.key)));$('source').value='quran_medium';$('variant').replaceChildren();[...new Set(rows.map(r=>r.variant))].sort().forEach(v=>$('variant').add(new Option(v,v)));
$('stats').textContent=generations.filter(g=>g.status==='success').length+' backgrounds generated · '+rows.filter(r=>r.status==='automated_pass').length+'/'+rows.length+' source/layout stress cases pass · 0 external reviews';
if(assessment.summary){const h=document.createElement('h2');h.textContent='Assessment';const p=document.createElement('p');p.textContent=assessment.summary;$('assessment').append(h,p);for(const f of assessment.families||[]){const d=document.createElement('p');const b=document.createElement('strong');b.textContent=f.name+': ';d.append(b,document.createTextNode(f.verdict));$('assessment').append(d)}}
function render(){const row=rows.find(r=>r.family===$('family').value&&r.variant===Number($('variant').value)&&r.format===$('format').value&&r.source_key===$('source').value);if(!row)return;page=Math.min(page,Math.max(0,row.pages.length-1));const p=row.pages[page];document.documentElement.style.setProperty('--phone',$('width').value+'px');$('label').textContent=row.reference+' · '+families[row.family];$('status').textContent=row.status==='automated_pass'?'Automated checks passed. Visual and source/context review still required.':'Not publishable in this test: '+row.errors.join(' ');$('card').hidden=!p;if(p)$('card').src=p.file+'?v='+p.sha256;$('raw').src=row.background;$('page').textContent=row.pages.length?(page+1)+' / '+row.pages.length:'No accepted complete composition';$('prev').disabled=page===0;$('next').disabled=page>=row.pages.length-1;$('record').textContent=JSON.stringify(sources.find(s=>s.key===row.source_key).record,null,2);$('audit').textContent=JSON.stringify({status:row.status,errors:row.errors,page:p},null,2);$('notes').textContent=(assessment.outputs||{})[row.id]||'No recorded Codex visual verdict for this exact composition.'}
['family','variant','format','source'].forEach(id=>$(id).onchange=()=>{page=0;render()});$('width').onchange=render;$('prev').onclick=()=>{page--;render()};$('next').onclick=()=>{page++;render()};render();
generations.filter(g=>g.status==='success').forEach(g=>{const f=document.createElement('figure'),i=document.createElement('img'),c=document.createElement('figcaption');i.src=g.file;i.loading='lazy';i.alt=families[g.family]+' background';c.textContent=families[g.family]+' · '+g.variant+' · '+g.format+' · '+g.seconds+'s';f.append(i,c);$('gallery').append(f)});
const q=new URLSearchParams(location.search);if(q.has('sheet')){const source=q.get('source')||'quran_medium',items=rows.filter(r=>r.source_key===source).flatMap(r=>r.pages.map((p,i)=>({r,p,i}))),n=Number(q.get('sheet'));$('main').replaceChildren();const title=document.createElement('h2');title.textContent='Phone audit · '+source+' · sheet '+(n+1)+'/'+Math.ceil(items.length/3);const wrap=document.createElement('div');wrap.className='sheet';items.slice(n*3,n*3+3).forEach(({r,p,i})=>{const f=document.createElement('figure'),c=document.createElement('figcaption'),img=document.createElement('img');c.textContent=families[r.family]+' · '+r.variant+' · '+r.format+' · page '+(i+1)+' · '+r.status;img.src=p.file;img.alt=c.textContent;f.append(c,img);wrap.append(f)});$('main').append(title,wrap)}
</script></html>'''


def build(directory):
    rows=json.loads((directory/'evaluation.json').read_text())
    generations=[json.loads(p.read_text()) for p in sorted(directory.glob('*_feed_4_5.json'))+sorted(directory.glob('*_story_9_16.json'))]
    sources=json.loads((Path(__file__).resolve().parents[1]/'tests/quality/sources.json').read_text())
    assessment=json.loads((directory/'assessment.json').read_text()) if (directory/'assessment.json').exists() else {}
    html=HTML
    for key,value in [('ROWS',rows),('GENERATIONS',generations),('SOURCES',sources),('ASSESSMENT',assessment)]:
        html=html.replace('__'+key+'__',json.dumps(value,ensure_ascii=False).replace('</','<\\/'))
    (directory/'review.html').write_text(html)
    counts={family:dict(Counter(r['status'] for r in rows if r['family']==family)) for family in sorted({r['family'] for r in rows})}
    (directory/'summary.json').write_text(json.dumps({'families':counts,'rendered_pages':sum(len(r['pages']) for r in rows),
        'generation_seconds':sum(g.get('seconds',0) for g in generations),'external_reviews':0,'release_ready':False},indent=2)+'\n')
    print(json.dumps(counts))


if __name__=='__main__':
    parser=argparse.ArgumentParser(description=__doc__);parser.add_argument('directory',type=Path)
    build(parser.parse_args().directory)
