"""Build a local, self-contained review UI for an existing quality bundle."""
import argparse
import json
from pathlib import Path


HTML = '''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Sabeel · Creator quality review</title><style>
*{box-sizing:border-box}body{margin:0;background:#f4f2e9;color:#1d322a;font:16px/1.5 system-ui,sans-serif}main{max-width:1160px;margin:auto;padding:24px}h1{font-size:32px;line-height:1.2;margin:12px 0}h2{font-size:21px}p{max-width:850px}.eyebrow{letter-spacing:.12em;font-size:12px;text-transform:uppercase}button,select{font:inherit;min-height:44px;border:1px solid #b5bcae;border-radius:8px;background:white;color:inherit;padding:8px 12px}button{cursor:pointer}button:disabled{opacity:.4;cursor:default}a{color:#285a46}label{display:inline-flex;flex-direction:column;font-size:13px;gap:5px}.controls{display:flex;gap:12px;flex-wrap:wrap;margin:22px 0}.notice{border-left:4px solid #a55b28;background:#fffaf0;padding:16px}.stats{font-size:19px;font-weight:650}table{border-collapse:collapse;width:100%;font-size:13px}td,th{text-align:left;padding:10px;border-bottom:1px solid #d8dacf}td button{font-size:12px}.tablewrap{overflow:auto}.review{display:flex;gap:26px;align-items:start;flex-wrap:wrap}.phone{width:var(--phone,320px);flex:none;background:#131d18;border-radius:22px;padding:0;overflow:hidden;box-shadow:0 10px 30px #1b312b1c}.phone img{width:100%;display:block}.details{max-width:600px;flex:1;min-width:240px}.pass{color:#326d47}.blocked{color:#9a481f}pre{white-space:pre-wrap;overflow-wrap:anywhere;font-size:12px}details{background:#fff9;padding:14px;margin:12px 0;border:1px solid #dedfd3;border-radius:10px}summary{cursor:pointer;min-height:34px}.batch{display:flex;gap:24px;align-items:start;flex-wrap:wrap}.batch figure{width:320px;margin:0}.batch img{width:320px;display:block}.batch figcaption{font-size:11px;line-height:1.35;min-height:42px}.batch h1{font-size:22px}.note{font-size:13px;color:#536256}.pagination{display:flex;gap:10px;align-items:center;margin:16px 0}#sourceText p{white-space:pre-wrap}#sourceText [lang=ar]{font-size:23px;line-height:2}body.sheet main{padding:16px}body.sheet .normal{display:none}@media(max-width:600px){main{padding:18px}.phone{max-width:100%}h1{font-size:27px}.details{min-width:100%}}
</style><main><div class="normal">
<div class="eyebrow">Sabeel Studio · 8 October 2026 · Actual application outputs</div>
<h1>Creator quality review</h1>
<div class="notice"><strong id="decision">Release held</strong><p id="counts" class="stats"></p><p>Automated checks, Codex visual assessment, and human review are separate evidence. No real creator or qualified source review has been completed. Manual review stays required.</p></div>
<p>Six verified sources × three design families × feed and Story = 36 complete compositions. A composition can contain several pages. Six fresh OpenAI photographs were generated through Sabeel’s background service and reused for the corresponding feed and Story cases.</p>
<p class="note">This controlled batch uses the olive palette, modern type, a creator signature, no reflection, and English-first reading order. It does not validate every brand, language, generated reflection, caption, or background. Phone sizes below are browser simulations.</p>
<h2>Inspect the finished output</h2><div class="controls"><label>Source<select id="source"></select></label><label>Design family<select id="family"></select></label><label>Format<select id="format"></select></label><label>Phone width<select id="width"><option value="320">320 px · compact</option><option value="390">390 px · standard</option></select></label></div>
<div class="review"><div><div id="phone" class="phone"><img id="preview" alt="Selected Sabeel card"></div><div class="pagination"><button id="prev">Previous page</button><span id="pageCount"></span><button id="next">Next page</button></div></div><div class="details"><h2 id="caseTitle"></h2><p id="caseState"></p><p id="findings"></p><div id="metrics"></div><details><summary>Exact source and provenance</summary><div id="sourceText"></div></details><details><summary>Page audit and immutable artifact identity</summary><pre id="audit"></pre></details></div></div>
<h2>All 36 cases</h2><div class="tablewrap"><table id="matrix"></table></div>
<h2>Human review tasks</h2><ol><li>Read every page at compact and standard phone widths. Judge hierarchy, references, visual credibility, identity, and willingness to publish under your own name.</li><li>For source review, check the full source record, translation attribution, narration, context, ordering, and every page boundary. Assess possible misunderstanding when a single slide is seen alone.</li><li>Record problems against the exact case and image digest. A changed output requires a new review. Do not approve a case you have not reviewed.</li></ol>
<p><a href="human-reviews.template.json" download>Download blank review declarations</a> · <a href="evaluation.json">Raw automated and visual evidence</a> · <a href="release-gate.json">Current release decision</a></p>
<p class="note">The external review format is evidence bookkeeping, not reviewer authentication. A responsible release owner must verify who reviewed and their qualifications. The command-line gate verifies image files, matrix completeness, all engineering checks, all source approvals, and at least 90% usable-without-repair creator ratings.</p></div><div id="sheet"></div></main>
<script>const rows=__ROWS__,sources=__SOURCES__,decision=__DECISION__;const $=id=>document.getElementById(id);let page=0;
const families={editorial:'Editorial typography',quiet_photography:'Quiet photography',minimal_paper:'Minimal paper'},formats={feed_4_5:'Feed · 4:5',story_9_16:'Story · 9:16'};
function option(select,value,label){const o=document.createElement('option');o.value=value;o.textContent=label;select.append(o)}
sources.forEach(s=>option($('source'),s.key,s.record.reference+' · '+s.key.split('_')[1]));Object.entries(families).forEach(([k,v])=>option($('family'),k,v));Object.entries(formats).forEach(([k,v])=>option($('format'),k,v));
function render(){const row=rows.find(r=>r.source_key===$('source').value&&r.family===$('family').value&&r.format===$('format').value),s=sources.find(s=>s.key===row.source_key),p=row.pages[page];$('phone').style.setProperty('--phone',$('width').value+'px');$('phone').hidden=!p;$('preview').src=p?p.file+'?v='+p.sha256:'';$('preview').alt=row.reference+' · '+(page+1)+' of '+row.pages.length;$('prev').disabled=page===0;$('next').disabled=page>=row.pages.length-1;$('pageCount').textContent=row.pages.length?(page+1)+' / '+row.pages.length:'No output';$('caseTitle').textContent=row.reference+' · '+families[row.family];$('caseState').className=row.automated_status==='passed'?'pass':'blocked';$('caseState').textContent='Automated: '+row.automated_status+' · '+row.pages.length+' pages';$('findings').textContent=row.errors.join(' ')||(row.agent_visual_assessment?row.agent_visual_assessment.notes:'Agent visual assessment not yet recorded.');$('metrics').textContent=p?'Lowest final-JPEG glyph contrast: '+Math.min(...p.audit.map(a=>a.jpeg_minimum_contrast))+':1. Body type and reference sizes are in the audit.':'';$('audit').textContent=JSON.stringify({artifact_digest:row.artifact_digest,page:p},null,2);$('sourceText').replaceChildren();for(const [lang,text] of [['en',s.record.translation_text],['ar',s.record.arabic_text]]){const e=document.createElement('p');e.lang=lang;e.dir=lang==='ar'?'rtl':'ltr';e.textContent=text;$('sourceText').append(e)}const pre=document.createElement('pre');pre.textContent=JSON.stringify(s,null,2);$('sourceText').append(pre)}
['source','family','format'].forEach(id=>$(id).onchange=()=>{page=0;render()});$('width').onchange=render;$('prev').onclick=()=>{page--;render()};$('next').onclick=()=>{page++;render()};$('counts').textContent=decision.automated_passed+'/36 cases pass automated checks · '+rows.reduce((n,r)=>n+r.pages.length,0)+' rendered pages';$('decision').textContent=decision.release_ready?'Release evidence complete':'Release held — further quality work and human review required';
const header=document.createElement('tr');['Source',...Object.values(families).flatMap(f=>[f+' · Feed',f+' · Story'])].forEach(t=>{const th=document.createElement('th');th.textContent=t;header.append(th)});$('matrix').append(header);sources.forEach(s=>{const tr=document.createElement('tr'),th=document.createElement('th');th.textContent=s.record.reference;tr.append(th);Object.keys(families).forEach(f=>Object.keys(formats).forEach(fmt=>{const row=rows.find(r=>r.source_key===s.key&&r.family===f&&r.format===fmt),td=document.createElement('td'),b=document.createElement('button');b.textContent=row.automated_status==='passed'?row.pages.length+' pages':'Blocked';b.className=row.automated_status==='passed'?'pass':'blocked';b.onclick=()=>{$('source').value=s.key;$('family').value=f;$('format').value=fmt;page=0;render();$('source').scrollIntoView({block:'start'})};td.append(b);tr.append(td)}));$('matrix').append(tr)});render();
const query=new URLSearchParams(location.search);if(query.has('batch')){document.body.classList.add('sheet');const pages=rows.flatMap(r=>r.pages.map((p,i)=>({r,p,i}))),batch=Number(query.get('batch')),items=pages.slice(batch*3,batch*3+3);const title=document.createElement('h1');title.textContent='Phone-size audit · '+(batch+1)+' / '+Math.ceil(pages.length/3)+' · 320 px';$('sheet').append(title);const grid=document.createElement('div');grid.className='batch';items.forEach(({r,p,i})=>{const figure=document.createElement('figure'),caption=document.createElement('figcaption'),img=document.createElement('img');caption.textContent=r.reference+' · '+families[r.family]+' · '+formats[r.format]+' · page '+(i+1)+'/'+r.pages.length;img.src=p.file+'?v='+p.sha256;img.alt=caption.textContent;figure.append(caption,img);grid.append(figure)});$('sheet').append(grid)}
</script></html>'''


def build(directory,sources_path):
    rows=json.loads((directory/'evaluation.json').read_text())
    decision=json.loads((directory/'release-gate.json').read_text())
    sources=json.loads(sources_path.read_text())
    html=HTML
    for key,value in [('ROWS',rows),('SOURCES',sources),('DECISION',decision)]:
        html=html.replace('__'+key+'__',json.dumps(value,ensure_ascii=False).replace('</','<\\/'))
    (directory/'review.html').write_text(html)
    template={r['id']:{'artifact_digest':r['artifact_digest'],
        'creator':{'reviewer':None,'date':None,'usable_without_repair':None,'notes':None},
        'qualified_source':{'reviewer':None,'date':None,'approved':None,'notes':None}} for r in rows}
    (directory/'human-reviews.template.json').write_text(json.dumps(template,indent=2)+'\n')


if __name__=='__main__':
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('directory',type=Path)
    parser.add_argument('--sources',type=Path,default=Path(__file__).resolve().parents[1]/'tests/quality/sources.json')
    args=parser.parse_args();build(args.directory,args.sources)
